import Head from "next/head";
import Image from "next/image";
import Logo from "../../public/images/logo.png";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import HeroHeader from "@/modules/HeroHeader";
import Spacer from "@/modules/Spacer";
import Nav from "@/modules/Nav";
import Footer from "@/modules/Footer";
import About from "@/modules/About";
import Skittles from "@/modules/Skittles";
import CDN from "@/modules/CDN";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <CDN />
      </Head>
      <main className="main">
        <Nav />
        <div className="child">
          <div className="trigger"></div>
          <HeroHeader />
          <About />
          <Skittles />
        </div>
        <Footer />
      </main>
    </>
  );
}
