import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import HeroHeader from "@/modules/HeroHeader";
import Spacer from "@/modules/Spacer";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

        <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.6.1/gsap.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.6.1/ScrollTrigger.min.js"></script>

        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="main">
        <div className="child">
          <div className="trigger"></div>
          <HeroHeader />
          <Spacer />
        </div>
      </main>
    </>
  );
}
